baseURL                        = "https://help.alwaysdata.com"
theme                          = "relearn"

ignoreFiles                    = [ "README.md" ]
refLinksErrorLevel             = "WARNING"

defaultContentLanguageInSubdir = "true"
languageCode                   = "en-us"
defaultContentLanguage         = "en"

[Taxonomies]
  tag = "tags"

[Languages]
  # i18n - EN
  [Languages.en]
    weight         = 1
    languageName   = "English"
    title          = "alwaysdata Documentation"
    [Languages.en.params]
      landingPageURL = "/en/"
    [Languages.en.menus]
      [[Languages.en.menus.shortcuts]]
        name   = "<i class='fab fa-fw fa-mastodon'></i> Mastodon"
        url    = "https://mastodon.social/@alwaysdata"
        weight = 11
      [[Languages.en.menus.shortcuts]]
        name   = "<i class='fab fa-fw fa-bluesky'></i> Bluesky"
        url    = "https://bsky.app/profile/alwaysdata.bsky.social"
        weight = 12
      [[Languages.en.menus.shortcuts]]
        name   = "<i class='fab fa-fw fa-linkedin'></i> LinkedIn"
        url    = "https://www.linkedin.com/company/alwaysdata/"
        weight = 13
      [[Languages.en.menus.shortcuts]]
        name   = "<i class='fab fa-fw fa-x-twitter'></i> X (Twitter)"
        url    = "https://twitter.com/alwaysdata"
        weight = 14
  # i18n - FR
  [Languages.fr]
    weight         = 2
    languageName   = "Français"
    title          = "Documentation alwaysdata"
    [Languages.fr.params]
      landingPageURL = "/fr/"
    [Languages.fr.menus]
      [[Languages.fr.menus.shortcuts]]
        name   = "<i class='fab fa-fw fa-mastodon'></i> Mastodon"
        url    = "https://mastodon.social/@alwaysdata"
        weight = 11
      [[Languages.fr.menus.shortcuts]]
        name   = "<i class='fab fa-fw fa-bluesky'></i> Bluesky"
        url    = "https://bsky.app/profile/alwaysdata.bsky.social"
        weight = 12
      [[Languages.fr.menus.shortcuts]]
        name   = "<i class='fab fa-fw fa-linkedin'></i> LinkedIn"
        url    = "https://www.linkedin.com/company/alwaysdata/"
        weight = 13
      [[Languages.fr.menus.shortcuts]]
        name   = "<i class='fab fa-fw fa-x-twitter'></i> X (Twitter)"
        url    = "https://twitter.com/alwaysdata"
        weight = 14

[outputs]
  home = [ "HTML", "RSS" ]

# Theme settings
[params]
  themeVariant             = "alwaysdata"
  disableBreadcrumb        = false
  disableNextPrev          = true
  disableShortcutsTitle    = false
  disableToc               = false
  disableLandingPageButton = true
  disableHoverBlockCopyToClipBoard = false
  disableInlineCopyToClipBoard = true
  landingPageURL           = "/"
  disableLanguageSwitchingButton = true
  disableGeneratorVersion = true
  disableHugoGeneratorInject = true
  showVisitedLinks         = false
  disableRootBreadcrumb    = true
  disableExplicitIndexURLs = true
  editURL                  = "https://github.com/alwaysdata/documentation/blob/master/content/"
  author.name              = "alwaysdata <contact@alwaysdata.com>"
